matrix:
  include:
    - language: node_js
      node_js: 
        - '12'
      cache: npm
      before_script:
        - cd javascript
      script:
        - npm install
        - npm test
    - language: csharp
      solution: dotnetCoreTDD.sln
      dotnet: 3.1
      mono: none     
      install:        
        - cd csharp
        - dotnet build
      script:
        - dotnet test
    - language: java
      jdk: openjdk11
      before_install:
        - chmod +x mvnw   
      install:
        - cd java
        - ./mvnw verify