matrix:
  include:
    - language: node_js
      node_js: 
        - '12'
      cache: npm
      before_script:
        - cd javascript
      script:
        - npm install
        - npm test
    - language: csharp
      solution: dotnetCoreTDD.sln
      dotnet: 3.1
      mono: none
      before_script:
        - pwd
        - cd csharp
      install:
        - dotnet build
        - dotnet test   