matrix:
  include:
    - language: node_js
      node_js: 
        - '12'
      cache: npm
      before_script:
        - cd javascript
      script:
        - npm install
        - npm test
    - language: csharp
      dotnet: 3.1
      before_script:
        - cd csharp
      install:
        - dotnet restore
      script:
        - dotnet build
        - dotnet test    