matrix:
  include:
    - language: node_js
      node_js: 
        - '12'
      cache: npm
      before_script:
        - cd javascript
      script:
        - npm install
        - npm test
    - language: csharp
      solution: dotnetCoreTDD.sln
      dotnet: 3.1
      mono: none
      before_script:
        - pwd
        - cd csharp
      install:
        - nuget restore dotnetCoreTDD.sln
        - nuget install xunit.runners -Version 2.4.0 -OutputDirectory testrunner
      script:
        - msbuild /p:Configuration=Release dotnetCoreTDD.sln
        - mono ./testrunner/xunit.runners.2.4.0/tools/xunit.console.clr4.exe ./TDDTraining.Tests/bin/Release/TDDTraining.Tests.dll       